#pragma once

#define WINDOW_WIDTH 1920
#define WINDOW_HEIGHT 1080
#define WINDOW_TITLE "raylib \"Lammies\""

#define TARGET_FPS 60

#define CURSOR_SIZE 64

#define MAX_CARDS 255
#define MAX_CARD_LOCKS MAX_CARDS
#define DECK_MAX 52

#define CARD_FLIP_TIME 0.125f

#define CARD_SIZE_SMALL (Vector2){80, 116}
#define CARD_SIZE (Vector2){168, 240}

#define CARD_HIGHLIGHT_EXTENT 5
#define CARD_SHADOW_OFFSET 8
#define CARD_SHADOW_DARKNESS 0.125f
#define CARD_SHADOW_ROUNDNESS 0.1f
#define CARD_SHADOW_SEGMENTS 4

#define OBJECT_SHADOW_OFFSET 16
#define OBJECT_SHADOW_DARKNESS 0.5f
#define RESERVE_STACK_OFFSET 6.0f
#define DISCARD_STACK_OFFSET 2.0f
#define OBJECT_PLACEMENT_INFLATE 15.0f
#define OBJECT_HOLD_OFFSET (CURSOR_SIZE * 0.5f)

#define MAX_OBJECTS 255
